export const BOOTSTRAP = 'BOOTSTRAP';

export const SET_LOADING = 'SET_LOADING';
export const RESET_LOADING = 'RESET_LOADING';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const USER_HAS_LOGGED_IN = 'USER_HAS_LOGGED_IN';
export const USER_HAS_LOGGED_OUT = 'USER_HAS_LOGGED_OUT';

export const ENTITY_REPOSITORY_HAS_CHANGED = 'ENTITY_REPOSITORY_HAS_CHANGED';

export const USER_HAS_JOINED = 'USER_HAS_JOINED';
export const USER_HAS_DISCONNECTED = 'USER_HAS_DISCONNECTED';

export const START_GAME = 'START_GAME';
export const LEAVE_GAME = 'LEAVE_GAME';
export const RESUME_GAME = 'RESUME_GAME';
export const PLAYER_GUESS = 'PLAYER_GUESS';
export const START_TURN = 'START_TURN';
export const FINISH_TURN = 'FINISH_TURN';


export const SHOW_CONFIRMATION_MODAL = 'SHOW_CONFIRMATION_MODAL';
export const CONFIRM_MODAL = 'CONFIRM_MODAL';
export const CANCEL_MODAL = 'CANCEL_MODAL';
